### ISSUE TITLE
Update windows node AMI for improved performance

### ISSUE THREAD

**Issue by gargana** [aws-quickstart/quickstart-amazon-eks-nodegroup#12]
The latest EKS Optimized Windows 2004 AMI has DSR (Direct Server Return) enabled by default during the kubelet bootstrap. 
This should mean no more port exhaustion on Windows nodes, better performance avoiding extra hops and reducing latency on the Windows HNS. https://techcommunity.microsoft.com/t5/networking-blog/direct-server-return-dsr-in-a-nutshell/ba-p/693710

**Comment by tlindsay42** [comment]
Completed at some point https://github.com/aws-quickstart/quickstart-amazon-eks-nodegroup/blob/7a6ebf13cb8bbfba50524645e8c3b3c890936d46/templates/amazon-eks-nodegroup.template.yaml#L329
