### ISSUE TITLE
Problem with NodeAutoscalingGroup parameter

### ISSUE THREAD

**Issue by nandexsp** [aws-quickstart/quickstart-amazon-eks-nodegroup#6]
In: 

  NodeAutoScalingGroup:
    Value: !If [IsManaged, !Ref ManagedASG, !Ref UnmanagedASG]

I get always the result None and it fails during the EKS creation. 
Im using the **amazon-eks.template.yaml**

and always is None and everything fails into the policy

**Comment by andrew-glenn** [comment]
Just came across this as well. Testing a fix.
